@startuml

top to bottom direction


actor "User" as User

package Игра {
    usecase "Выбор режима и типа игры" as UC1
    usecase "Запуск игры против компьютера" as UC2
    usecase "Запуск игры против другого пользователя" as UC3
}
package Результаты {
    usecase "Сохранение результата в таблицу рекордов" as UC4
    usecase "Отображение таблицы рекордов" as UC5
}
    User --> UC1 : Выбирает режим и тип игры
    UC2 ---> UC4 : Окончание игры
    UC3 --> UC4 : Окончание игры
    UC4 --> UC5 : Внесение результата
    User -> UC5 : Просмотр таблицы рекордов

    UC1 -down-> UC2 : запуск игры
    UC1 -down-> UC3 : запуск игры


@enduml
