@startuml
start

:Открыть форму выбора режима игры;

if (Выбран режим "Против компьютера") then (Да)
  :Открыть форму выбора типа игры;
  if (Выбран тип "По времени") then (Да)
    :Запустить игру против компьютера по времени;
  else (Нет)
    :Запустить игру против компьютера по счёту;
  endif
else (Нет)
  :Открыть форму выбора типа игры;
  if (Выбран тип "По времени") then (Да)
    :Запустить игру против другого пользователя по времени;
  else (Нет)
    :Запустить игру против другого пользователя по счёту;
  endif
endif

stop
@enduml
